name: scp-test
on:
  workflow_dispatch:

jobs:
  provision:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply --auto-approve